FROM microsoft/aspnetcore-build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -o out
ENTRYPOINT ["dotnet", "out/Orquestador.dll"]